#! /usr/bin/env python
# encoding: utf-8

bld.program(
    features='cxx test',
    source=['template_tests.cpp'] + bld.path.ant_glob('src/*.cpp'),
    target='template_tests',
    use=['template', 'gtest'])
