// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: abacus/protobuf/kind.proto

#include "abacus/protobuf/kind.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace abacus {
namespace protobuf {
}  // namespace protobuf
}  // namespace abacus
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_abacus_2fprotobuf_2fkind_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_abacus_2fprotobuf_2fkind_2eproto = nullptr;
const ::uint32_t TableStruct_abacus_2fprotobuf_2fkind_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;
const char descriptor_table_protodef_abacus_2fprotobuf_2fkind_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\032abacus/protobuf/kind.proto\022\017abacus.pro"
    "tobuf*,\n\004Kind\022\013\n\007COUNTER\020\000\022\014\n\010CONSTANT\020\001"
    "\022\t\n\005GAUGE\020\002B\021Z\017abacus/protobufb\006proto3"
};
static ::absl::once_flag descriptor_table_abacus_2fprotobuf_2fkind_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_abacus_2fprotobuf_2fkind_2eproto = {
    false,
    false,
    118,
    descriptor_table_protodef_abacus_2fprotobuf_2fkind_2eproto,
    "abacus/protobuf/kind.proto",
    &descriptor_table_abacus_2fprotobuf_2fkind_2eproto_once,
    nullptr,
    0,
    0,
    schemas,
    file_default_instances,
    TableStruct_abacus_2fprotobuf_2fkind_2eproto::offsets,
    nullptr,
    file_level_enum_descriptors_abacus_2fprotobuf_2fkind_2eproto,
    file_level_service_descriptors_abacus_2fprotobuf_2fkind_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_abacus_2fprotobuf_2fkind_2eproto_getter() {
  return &descriptor_table_abacus_2fprotobuf_2fkind_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_abacus_2fprotobuf_2fkind_2eproto(&descriptor_table_abacus_2fprotobuf_2fkind_2eproto);
namespace abacus {
namespace protobuf {
const ::google::protobuf::EnumDescriptor* Kind_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_abacus_2fprotobuf_2fkind_2eproto);
  return file_level_enum_descriptors_abacus_2fprotobuf_2fkind_2eproto[0];
}
bool Kind_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace protobuf
}  // namespace abacus
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
