name: Clang-Format
on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *" # 3 AM CET
  push:
  pull_request:
jobs:
  clang-format:
    name: ClangFormat
    runs-on: [self-hosted, docker]
    steps:
      - uses: steinwurf/clang-format-action
