name: Cppcheck
on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *" # 3 AM CET
  push:
  pull_request:
jobs:
  build:
    name: cppcheck
    runs-on: [self-hosted, linux]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cppcheck
        uses: deep5050/cppcheck-action@main

