name: Cppcheck
on:
  push:
  pull_request:

jobs:
  build:
    name: cppcheck
    runs-on: [self-hosted, linux]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cppcheck
        uses: deep5050/cppcheck-action@main
        with:
          other_options: --verbose
